name: bomwater_nb_env
channels:
  - conda-forge
dependencies: 
  - python=3.7
  - pandas
  - numpy
  - matplotlib
  - voila
  - ipyfilechooser
  - jupyterlab 
  - ipywidgets
  - ipyleaflet
  - jupyter
  - sidecar
  - pint
  - pip
  - pip:
    # will add link to bomwater python package once deployed on pypi
    # installing manaully for now