name: bomwater_nb_env
channels:
  - conda-forge
dependencies: 
  - python=3.7
  - pandas
  - numpy
  - matplotlib
  - voila
  - ipyfilechooser
  - jupyterlab 
  - ipywidgets
  - ipyleaflet
  - jupyter
  - sidecar
  - pint
  - pip
  - pip:
    - bomwater
